package org.exceptions.handling;

public class InnerTryCatchFinally {

}
